from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def read_repo_file(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def test_dockerfile_builds_frontend_and_runs_one_app_worker() -> None:
    dockerfile = read_repo_file("Dockerfile")

    assert (
        "node:22-bookworm-slim@sha256:6c74791e557ce11fc957704f6d4fe134a7bc8d6f5ca4403205b2966bd488f6b3"
        in dockerfile
    )
    assert (
        "python:3.12-slim-bookworm@sha256:d50fb7611f86d04a3b0471b46d7557818d88983fc3136726336b2a4c657aa30b"
        in dockerfile
    )
    assert "npm ci" in dockerfile
    assert "npm run build" in dockerfile
    assert "COPY --from=frontend-build" in dockerfile
    assert "--require-hashes -r requirements.prod.lock" in dockerfile
    assert "--uid 10001 --gid 10001" in dockerfile
    assert 'USER app' in dockerfile
    assert '"backend.main:app"' in dockerfile
    assert '"--workers", "1"' in dockerfile
    assert "HEALTHCHECK" in dockerfile
    assert "/health" in dockerfile
    assert "chown -R app:app /app" not in dockerfile
    assert "chown app:app /app/outputs" in dockerfile


def test_production_requirements_lock_is_hash_pinned() -> None:
    lock = read_repo_file("requirements.prod.lock")

    assert "generated by pip-compile" in lock
    assert "--hash=sha256:" in lock
    assert "pytest" not in lock
    assert "pytest-asyncio" not in lock


def test_dockerignore_excludes_secrets_and_generated_files() -> None:
    ignored = set(read_repo_file(".dockerignore").splitlines())

    assert ".env" in ignored
    assert ".env.*" in ignored
    assert "outputs/" in ignored
    assert ".git/" in ignored
    assert "venv/" in ignored
    assert "frontend/node_modules/" in ignored
